TRUNCATE role CASCADE;

TRUNCATE user_entity CASCADE;

TRUNCATE question CASCADE;

TRUNCATE answer CASCADE;

TRUNCATE tag CASCADE;

TRUNCATE question_has_tag CASCADE;

TRUNCATE reputation CASCADE;

TRUNCATE votes_on_questions CASCADE;

TRUNCATE question_viewed CASCADE;

TRUNCATE tag_ignore CASCADE;